Scooter rent app
Andrisssd/c-sharp-syllabus-Homework pull request #10
Opened 2021-12-11 11:25 UTC by Andrisssd

2021-12-12 09:37 UTC, ausmoons requested changes

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +                for (decimal i = 0; i < Math.Floor((decimal)totalMinutesInRent.TotalMinutes); i++)
Kāpēc tev vajag šo loop te?

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public void StartRent(string id, Dictionary<string, Scooter> dictionary, DateTime time)
Nebija labāk izmantot tikai šo, bet tās otras metodes?

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public decimal CountRentForActiveScooters(string id, Dictionary<string, Scooter> dictionary, DateTime functionCallTime)
Tu padot atseviški katru scooter? Tad jābūt CountRentForActiveScooter vai arī izmanto šo metodi, lai tā atgrieztu priekš visiem scooters

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/Scooter.cs
> +        private static int _totalSeriesNumber { get; set; }
Private neizmanto { get; set; }

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +        public void Get_Scooter_By_Id_0x003()
Testu nosaukum Metode_KoPadod_KoSagaida. Testu mapē ir piemērs

2021-12-12 09:37 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +        public void Get_Scooter_By_Id_0x003()
Vajag arī // Arrange // Act // Assert komentārus

2021-12-12 11:19 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +                for (decimal i = 0; i < Math.Floor((decimal)totalMinutesInRent.TotalMinutes); i++)
Itereju katru minuti kopsh scootera _rentTimeStart'a lidz tam DateTime kad tika izsaukts EndRent

2021-12-12 17:41 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +                for (decimal i = 0; i < Math.Floor((decimal)totalMinutesInRent.TotalMinutes); i++)
Tev tiešām ir jāiterē cauri tai VISAI loģikai?

2021-12-13 06:33 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +                for (decimal i = 0; i < Math.Floor((decimal)totalMinutesInRent.TotalMinutes); i++)
Visprecizakais risinajums ko izdomaju, domaju ka drikst izdarit to daudz optimizetako bet nevaru izdomat ka to realizet

2021-12-16 09:38 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public decimal CalculateIncome(int year, bool includeNotCompletedRentals, Dictionary<string, Scooter> scooters, DateTime callTime)
interfeisā nav šitādas metodes..

2021-12-16 09:39 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public decimal CalculateIncome(bool includeNotCompletedRentals, Dictionary<string, Scooter> scooters, DateTime callTime)
šitādas metodes interfeisā nav.

2021-12-16 09:40 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public string Name => "Rent.Comp.Express";
kā izveidosi kompāniju ar citu nosaukumu?

2021-12-16 09:40 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public Dictionary<int, decimal> YearAndTotalIncome;
interfeisā nav šāda prop.

2021-12-16 09:40 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public Dictionary<int, decimal> YearAndTotalIncomeCompletedRentalsFalse;
interfeisā nav šāda prop.

2021-12-16 09:41 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        const int TOTAL_MINUTES_IN_DAY = 1440;
kompānijai tiešām jāzin dienas garums minūtēs?

2021-12-16 09:42 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        public decimal EndRent(string id, Dictionary<string, Scooter> dictionary, DateTime functionCallTime)
vai tiešām tā ir kompānija kas izrēķina rēķinu par sniegto pakalpojumu? 
vairāk jautājums par to vai aprēķinam tiešām jābūt šeit? 
un ja tas mainās? vai kompānija ir starptautiska? katrā valstī aprēķins atšķirsies.

2021-12-16 09:43 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +            if (!dictionary[id].IsRented)
un ja tajā dictionary nav tāds scooteris nekad bijis?

+ cik zinu interfeisā nav metode start rent ar 2 argumentiem.

2021-12-16 09:44 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/RentalCompany.cs
> +        //Overload needed for tests
priekš testēšanas ir interfeiss.. šeit viss kas ir vajadzīgs extra būs privāts noteikti..

2021-12-16 09:44 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +            newScooter.IsRented = false;
bool defaut value ir false.

2021-12-16 09:45 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +                return _scooterDictionary[scooterId];
dictionary.ContainsKey() ?

2021-12-16 09:45 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +                throw new Exception("Error 001 || ScooterService line 34");
pārāk generic un nekādā veidā nepaskaidro problēmu.

2021-12-16 09:46 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +            return _scooterDictionary;
cik atceros tad interfeisā bija List<Scooter>

2021-12-16 09:47 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +                _scooterDictionary.Remove(id);
containsKey() ?

2021-12-16 09:47 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentApp/ScooterService.cs
> +                throw new Exception("Error 002 || ScooterService line 52");
pārāk generic un nepaskaidro problēmu.

2021-12-16 09:48 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +        public void Remove_One_Scooter()
RemoveScooter_Add2Scooters_Remove1_scooter_shouldHave1Scooter

2021-12-16 09:49 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +            Scooter scooter = new Scooter("0x003", 0.05M);
visi scooter service testi jāraksta pret interfeisu. :) 
aka IScooterService service = new ScooterService();

2021-12-16 09:49 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +            scooter.StartRent(startTime);
interfeisā nav šādas metodes.

2021-12-16 09:51 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/csharp-basics/exercises/ScooterRentApp/ScooterRentAppTests/ScooterRentTests.cs
> +            RentalCompany company = new RentalCompany();
pret interfeisu tests jāraksta.

2021-12-16 09:52 UTC, EdgarsSalmins requested changes
Testi jāraksta pret interfeisiem.. komentāros ieliku piemēru.. 
testi jānodala.. Rental Company testi atsevišķi.. Scooter service testi atsevišķi.. 
neredzēju nevienu Custom exception klasi uztaisītu.. :) tas bija uzdevuma prasībās.
visur komentārus nesarakstīju jo ļoti daudz kas atkārtojas. :) balstoties uz šiem komentāriem salabo visu cik tālu vari.. :) kur nav skaidrs prasi. :)

2021-12-19 14:47 UTC, closed without merging