Main if risks
Andrisssd/c-sharp-syllabus-Homework pull request #23
Opened 2022-01-12 22:28 UTC by Andrisssd

2022-01-14 19:06 UTC, ausmoons requested changes

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Risk.cs
> +            Name = name;
Priekš kam tev šeit ir šis?

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Validator.cs
> +                if (policy.ValidTill == validTill && policy.ValidFrom == validFrom)
tiešām if vai else if?

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Validator.cs
> +        public static bool PolicyIsValid(string nameOfInsuredObject, DateTime validFrom, short validMonths, IList<Policy> policyList)
IsPolicyValid

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Validator.cs
> +                {
Kāda atšķirībsa no iepriekšējā if?

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/RisksTests/InsuranceCompanyTests.cs
> +            int actualCount = _insuranceCompany.GetPolicy("Policy", new DateTime(2000, 10, 10, 10, 10, 10)).InsuredRisks.Count();
_insuranceCompany.GetPolicy("Policy", new DateTime(2000, 10, 10, 10, 10, 10)) -- šo var likt pa act daļas

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/RisksTests/InsuranceCompanyTests.cs
> +            IPolicy policy = _insuranceCompany.GetPolicy(nameOfInsuredObject, new DateTime(2000, 11, 9));
šis ir act

2022-01-14 19:06 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/RisksTests/InsuranceCompanyTests.cs
> +            Assert.AreEqual(expectedPolicyName, actualPolicyName);
Assert.AreEqual(expectedPolicyName, policy.NameOfInsuredObject);

2022-01-15 11:48 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/InsuranceCompany.cs
> +        public IPolicy GetPolicy(string nameOfInsuredObject, DateTime effectiveDate)
Man tachu ir klase Policy kura inherit IPolicy, es nesaprotu

2022-01-15 11:51 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Risk.cs
> +            Name = name;
Lai viegli taisit riskus

2022-01-17 19:18 UTC, ausmoons approved these changes

2022-01-17 19:18 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Risk.cs
> +            Name = name;
Kā vakar rakstīju konstruktorā liek private vai public tikai ar get

2022-01-17 19:33 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/RiskApp/RiskBodies/Risks/Risk.cs
> +            Name = name;
Jau aizmirsu ka taisit objektus bez konstruktora :D

2022-01-17 19:35 UTC, merged