Collections
Andrisssd/c-sharp-syllabus-Homework pull request #8
Opened 2021-12-03 13:20 UTC by Andrisssd

2021-12-03 20:36 UTC, ausmoons requested changes

2021-12-03 20:36 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(var name in names)
TU izmanto hashsetu un pāŗbaudi unique names?

2021-12-03 20:36 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/Collections/Histogram/Program.cs
> +        private const string _path = @"C:\Users\User\Desktop\homework\c-sharp-syllabus-Homework\c-sharp-syllabus-main\csharp-basics\exercises\Collections\Histogram\midtermscores.txt";
Path likt tādu, lai nenorāda uz tavu datoru -> ../../..

2021-12-04 05:59 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(var name in names)
Ta ir kl'uda?

2021-12-04 18:27 UTC, ausmoons commented on c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(var name in names)
Kādas ir hashet īpašības?

2021-12-04 18:28 UTC, ausmoons approved these changes

2021-12-04 19:14 UTC, Andrisssd commented on c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(var name in names)
ka vin'a nav dublicatu

2021-12-04 19:14 UTC, merged